Applicationlogictasks
Ellerden/Test-Guru pull request #11
Opened 2018-11-17 12:55 UTC by Ellerden

2018-11-17 20:56 UTC, iBublik requested changes

2018-11-17 20:56 UTC, iBublik commented on app/controllers/answers_controller.rb
> +  before_action :set_answer, only: %i[show edit update destroy]
Соблюдай единообразие в нейминге - выше подобный коллбэк называется `find`, здесь `set`

2018-11-17 20:56 UTC, iBublik commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit(:text, :correct, :question_id)
Связь с вопросом нужно сделать через ассоциацию, а не через параметры

2018-11-17 20:56 UTC, iBublik commented on app/controllers/participations_controller.rb
> +    @test = @participation.test
По названию метода никогда не поймешь, что он 2 переменные выставляет разом. Так лучше не делать.

2018-11-17 20:56 UTC, iBublik commented on app/controllers/questions_controller.rb
> +    render :tests
Тут будет попытка рендеринга щаблона `tests`. Я такого не нашел, значит это упадет с 500 ошибкой

2018-11-17 20:56 UTC, iBublik commented on app/controllers/tests_controller.rb
> +  # пока нет VIEW и ФОРМЫ которые бы позволяли редактировать тест
Используй ту же форму, что и для `new`

2018-11-17 20:56 UTC, iBublik commented on app/controllers/tests_controller.rb
> + # пока нет VIEW и ФОРМЫ которые бы позволяли создавать новый тест
Неужели этого не было в скринкастах? Даже если нет, то надо сделать, по аналогии с формами для других ресурсов

2018-11-17 20:56 UTC, iBublik commented on app/models/participation.rb
> +    if correct_answer?(answer_ids)
Однострочник бы лучше смотрелся

2018-11-17 20:56 UTC, iBublik commented on app/models/participation.rb
> +    test.questions.size - questions_left
Можно сделать чуточку эффективнее - 1 запросом. Посмотри на то, как определяется следующий вопрос в методе `next_question`. Запрос будет очень похожий

2018-11-17 20:56 UTC, iBublik commented on app/models/participation.rb
> +    test.questions.size - questions_left
Метод questions_left еще ближе к тому, что требуется. Доработай его

2018-11-17 20:56 UTC, iBublik commented on app/models/participation.rb
> +    ((correct_questions.to_f / test.questions.size) * 100)
Внешние скобки лишние

2018-11-17 20:56 UTC, iBublik commented on app/models/participation.rb
> +    # т.к. по какой-то причине в answer_ids первый элемент всегда ""
Нужно указать опцию `include_hidden: false`, когда создаешь чекбоксы. Подробнее об этом посмотри в документации

2018-11-17 20:56 UTC, iBublik commented on app/models/participation.rb
> +    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
Обработай ситуацию, когда с клиента приходит nil (пользователь не выбрал ни одного ответа)

2018-11-17 20:56 UTC, iBublik commented on app/models/test.rb
> +  def self.by_category(_category)
Вообще этот метод должен возваращать тесты, у которых заголовок категории равен заданному. Так что параметр нужен, просто ты его не используешь в методе

2018-11-17 20:56 UTC, iBublik commented on app/models/user.rb
> +    participations.order(id: :desc).find_by(test_id: test.id)
`find_by(test: test)`

2018-11-17 20:56 UTC, iBublik commented on app/views/participations/index.html.erb
> +<% if @tests.present? %>
Для чего этот шаблон? У тебя же нет экшна index в роутах

2018-11-17 20:56 UTC, iBublik commented on app/views/questions/edit.html.erb
> +<%= render 'form', test: nil%>
Зачем в форму передавать переменную, которая там не используется?

2018-11-17 20:56 UTC, iBublik commented on app/views/shared/_footer.html.erb
> +  <a href="https://thinknetica.com"> Thinknetica </a>
Открывай внешние ссылки в новой вкладке

2018-11-17 20:56 UTC, iBublik commented on app/views/tests/_test.html.erb
> +<% if test.questions.present? %>
Не особо полезная проверка. В реальной системе тесты без вопросов не могли бы быть опубликованы. Так что это лишнее усложнение

2018-11-19 12:04 UTC, Ellerden commented on app/controllers/tests_controller.rb
> + # пока нет VIEW и ФОРМЫ которые бы позволяли создавать новый тест
В скринкасте, кажется, не было. Я думала создать формы как с другими ресурсами, тут нет ничего сложного, на данном этапе пока решила не делать. Это были комменты для меня - что в тестах пока не все вьюхи. Добавлю все вьюхи.

2018-11-19 12:28 UTC, Ellerden commented on app/views/questions/edit.html.erb
> +<%= render 'form', test: nil%>
Изначально у меня не работало адекватно form_with, если я указывала только один параметр question: @question, не указывая параметры test, поэтому я явно прописывала test, даже если он nil. Проверила сейчас - этого бага больше нет, так что уберу test nil, спасибо.

2018-11-19 12:34 UTC, Ellerden commented on app/views/tests/_test.html.erb
> +<% if test.questions.present? %>
У меня пока в системе это единственный раз проверка на то, содержит ли тест вопросы или нет, поэтому если я ее здесь убираю - то тест без вопросов можно пройти и выпадает ошибка. Поэтому я ввела эту проверку здесь, и оставила бы ее пока тут.

2018-11-20 20:01 UTC, iBublik commented on app/controllers/participations_controller.rb
> +    @test = @participation.test
А стоит под это метод выделять? Почему бы не обращаться к тесту через `@participation`?

2018-11-20 20:01 UTC, iBublik commented on app/models/participation.rb
> +    correct_answers.ids.sort == answer_ids.map(&:to_i).sort if answer_ids
Дополнительные проверки усложняют код. Тут можно избежать ее, если в `answer_ids` гаранитрованно будет массив. Используй `Array(answer_ids)`, чтоб всегда работать с массивом

2018-11-20 20:01 UTC, iBublik commented on app/views/questions/edit.html.erb
> +<%= render 'form', test: nil%>
Так могло быть, если ты использовала _локальные_ переменные. При обращении к несуществующей локальной переменной падает ошибка. А вот инстанс-переменные инициализируются при первом обращении к ним

2018-11-20 20:02 UTC, iBublik approved these changes

2018-11-21 08:35 UTC, merged