Userauthenticationtasks
Ellerden/Test-Guru pull request #12
Opened 2018-11-23 22:51 UTC by Ellerden

2018-11-25 07:13 UTC, iBublik requested changes

2018-11-25 07:13 UTC, iBublik commented on app/controllers/application_controller.rb
> +    session[:forwarding_url] = request.original_url if request.get?
Всегда писать в сессию избыточно. Делай это только если пользователь не авторизован

2018-11-25 07:13 UTC, iBublik commented on app/controllers/application_controller.rb
> +    cookies[:username] = current_user&.username
Это для чего?

2018-11-25 07:13 UTC, iBublik commented on app/controllers/participations_controller.rb
> +  before_action :authenticate_user!
Можно это поместить в ApplicationController, а где не требуется сделать `skip_before_action`

2018-11-25 07:13 UTC, iBublik commented on app/controllers/sessions_controller.rb
> +    @current_user = session[:user_id] = nil
Из сессии лучше удалять с помощью `delete`

2018-11-25 07:13 UTC, iBublik commented on app/controllers/sessions_controller.rb
> +      redirect_to session[:forwarding_url]
В сессии может быть пусто, в этом случае нужно иметь fallback url

2018-11-25 07:13 UTC, iBublik commented on app/controllers/tests_controller.rb
> +    @user = @current_user
Тебе больше не нужен `@user`, используй `current_user` (именно метод, а не переменную - метод может содержать доп. логику, да и интсанс-переменная может поменять название)

2018-11-25 07:13 UTC, iBublik commented on app/helpers/flash_helper.rb
> +  def flash_message
Хелпер должен быть универсальнее - выводить любой тип флеша (тип передается параметром). От типа так же зависит класс флеша

2018-11-25 07:13 UTC, iBublik commented on app/models/user.rb
> +                    format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
Сложные регулярные выражения в этом случае бесполезны - https://davidcel.is/posts/stop-validating-email-addresses-with-regex/

2018-11-25 07:13 UTC, iBublik commented on app/models/user.rb
> +                    format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
Проверку стоит всегда делать. Вдруг у нас появится возможность поменять email, а у тебя код на это не расчитан

2018-11-25 07:13 UTC, iBublik commented on app/views/sessions/_form.html.erb
> +    <%= f.label :username %>
Зачем заставлять пользователя придумывать username? Сейчас email служит универсальным логином. Большинство пользователей откажутся от регистрации из-за нежелания придумывать себе логин :)

2018-11-25 07:13 UTC, iBublik commented on db/schema.rb
>      t.string "email", null: false
Не вижу уникального индекса на это поле. Без него уникальность "не настоящая" - рельсы сделают запрос в базу на наличие записи с таким email, а потом отправят запрос на сохранение. Между этими 2 запросами есть окно, в котором может быть создан дубликат. В таких случаях поможет только контроль целостности на уровне СУБД

2018-11-25 10:07 UTC, Ellerden commented on app/controllers/application_controller.rb
> +    cookies[:username] = current_user&.username
cookies[:username] = current_user&.username
это из скринкаста, я проверяла. забыла удалить

2018-11-26 06:18 UTC, iBublik approved these changes

2018-11-26 06:18 UTC, iBublik commented on app/controllers/application_controller.rb
> +    session[:forwarding_url] = request.original_url if request.get? && current_user.nil?
У тебя строкой ниже проверяется залогинен ли пользователь. Объедини это все вместе

2018-11-26 06:18 UTC, iBublik commented on app/controllers/sessions_controller.rb
> +      redirect_to session[:forwarding_url].present? ? session[:forwarding_url] : root_path
`redirect_to session.delete(:forwarding_url) || root_path`

2018-11-26 06:18 UTC, iBublik commented on app/controllers/tests_controller.rb
> +    @user = current_user
Не нужен тебе `@user` больше. Зачем заводить отдельную переменную, когда везде доступен `current_user`

2018-11-27 14:26 UTC, merged