Devisetasks
Ellerden/Test-Guru pull request #13
Opened 2018-11-29 12:00 UTC by Ellerden

2018-11-29 16:57 UTC, iBublik requested changes

2018-11-29 16:57 UTC, iBublik commented on app/controllers/admin/base_controller.rb
> +    redirect_to root_path, alert: 'У вас нет прав для просмотра этой страницы' unless current_user.is_a?(Admin)
Проверку на админство стоит вынести в модель - это много где используется

2018-11-29 16:57 UTC, iBublik commented on app/controllers/application_controller.rb
> +  def after_sign_in_path_for(resource)
У нас только один аутентифицируемый ресурс - user. Не используй абстрактный нейминг там, где можно написать более конкретно и понятно

2018-11-29 16:57 UTC, iBublik commented on app/controllers/application_controller.rb
> +    flash[:notice] = "Привет, #{current_user.first_name} #{current_user.last_name}!"
От этого метода ожидается только то, что он вернет url. То что он устанавливает флеш - побоычный и совсем неожиданный эффект. Так лучше не делать, код становится запутанным и тяжело тестируемым. Устанавливать флеш стоит в экшне контроллера сессий

2018-11-29 16:57 UTC, iBublik commented on app/controllers/application_controller.rb
> +      stored_location_for(resource) || root_path
Можно просто сделать `super`

2018-11-29 16:57 UTC, iBublik commented on app/controllers/application_controller.rb
> +    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :email, :password, :password_confirmation])
Ключи повторяются - можно вынести в локальную переменную, тут вызовы сократятся

2018-11-29 16:57 UTC, iBublik commented on app/controllers/questions_controller.rb
>  class QuestionsController < ApplicationController
Зачем эти контроллеры оставлять для пользователя? Ему по сути нужен только список тестов и прохождение теста

2018-11-29 16:57 UTC, iBublik commented on app/models/admin.rb
> +  validates :last_name, presence: true
`validates :first_name, :last_name, presence: true` - можно несколько валидаций разом описать

2018-11-29 16:57 UTC, iBublik commented on app/models/user.rb
> +  validates :last_name, presence: true
Раз эти валидации есть в базовом классе, зачем их в Admin дублировать?

2018-11-29 17:18 UTC, Ellerden commented on app/models/user.rb
> +  validates :last_name, presence: true
Сорри, забыла удалить после скринкаста. Сначала валидации были только для админа.

2018-11-30 03:05 UTC, iBublik requested changes

2018-11-30 03:05 UTC, iBublik commented on app/controllers/application_controller.rb
>      if current_user.is_a?(Admin)
Используй параметр, а не current_user, чтоб не лезть в базу 2й раз

2018-11-30 03:05 UTC, iBublik commented on app/controllers/sessions_controller.rb
> +  after_action :say_greetings_flash, only: %i[create]
Зачем это в after_action помещать? В самом экшне сделай

2018-11-30 03:05 UTC, iBublik commented on app/models/admin.rb
> +    redirect_to root_path, alert: 'У вас нет прав для просмотра этой страницы' unless current_user.is_a?(Admin)
Модель ничего не знает (да и не должна) про редиректы, это не ее ответственность

2018-11-30 06:56 UTC, Ellerden commented on app/controllers/sessions_controller.rb
> +  after_action :say_greetings_flash, only: %i[create]
Да, спасибо, чего-то я намудрила тут.

2018-11-30 06:57 UTC, Ellerden commented on app/models/admin.rb
> +    redirect_to root_path, alert: 'У вас нет прав для просмотра этой страницы' unless current_user.is_a?(Admin)
Спасибо, поправила это.

2018-11-30 21:13 UTC, merged