Apigisttasks
Ellerden/Test-Guru pull request #16
Opened 2018-12-09 16:03 UTC by Ellerden

2018-12-09 18:41 UTC, iBublik requested changes

2018-12-09 18:41 UTC, iBublik commented on app/controllers/participations_controller.rb
> +    rescue Octokit::Error
Эту ошибку лучше обработать в самом сервисе, потому что это его "кишочки", и они должны быть скрыты снаружи. Лучше, чтоб было так:
```ruby
if result.success?
  current_user.gists.create(...)
else
  redirect_to ...
end
```

2018-12-09 18:41 UTC, iBublik commented on app/services/gist_question_service.rb
> +      description: I18n.t('.gist_description', test_title: @test.title),
Не используй тут относительную ссылку - она неправильно раскроется

2018-12-09 18:41 UTC, iBublik commented on app/services/gist_question_service.rb
> +    content = [@question.text]
Можно чуть компактнее - `[@question.text, *@question.answers.pluck(:text)].join("\n")`

2018-12-09 18:41 UTC, iBublik commented on app/views/admin/gists/_gist.html.erb
> +    <a target="_blank" href="<%= admin_question_path(gist.question) %>"><%= gist.question.text.truncate(25) %></a>
Зачем вручную ссылки строить, когда есть `link_to`?
Используй хелпер truncate, а не метод строки - он лучше подходит для задачи отображения обрезанной строки

2018-12-09 18:41 UTC, iBublik commented on app/views/shared/_flash.html.erb
> +   <%= content_tag :div, sanitize(message), class: [:alert, alert_for(type)]%>
Вот поэтому у тебя и отрезается target - https://stackoverflow.com/questions/29786876/rails-removes-target-blank

2018-12-09 18:41 UTC, iBublik commented on config/locales/en.yml
> +  gist_description: "A question about \"%{test_title}\" from TestGuru"
Это стоит поместить в неймспейс services + неймспейс конкретного сервиса, в котором эта локаль нужна

2018-12-09 18:41 UTC, iBublik commented on config/routes.rb
> +    resources :gists, shallow: true, only: :index
Если только index, то зачем там shallow?

2018-12-09 18:41 UTC, iBublik commented on db/migrate/20181209133816_rename_gist_hash_to_gist_url_in_gists.rb
> +    rename_column :gists, :gist_hash, :gist_url
Если это в рамках задачи изменяется, то лучше откатить миграцию, переименовать поле и заново ее накатить. Иначе очень много миграций плодится

2018-12-09 20:40 UTC, Ellerden commented on app/views/shared/_flash.html.erb
> +   <%= content_tag :div, sanitize(message), class: [:alert, alert_for(type)]%>
а, поняла. хм... просто без sanitize у меня ссылка не выводилась нормально во флэше. она нам была но в виде "<a href=""> "и не была кликабельна, поэтому я долго искала чего можно сделать и нашла sanitize.

2018-12-09 20:44 UTC, Ellerden commented on app/services/gist_question_service.rb
> +      description: I18n.t('.gist_description', test_title: @test.title),
а можешь уточнить тут почему, у меня тут был затык с тем, что просто t('.gist_description', test_title: @test.title) пришлось добавить I18n чтобы все норм раскрывалось и я вроде бы решила проблему (у меня сначала был полный путь до локализации, но мне удалось редуцировать его до вот того что есть и я подумала что это есть хорошо)

2018-12-09 21:14 UTC, Ellerden commented on app/views/admin/gists/_gist.html.erb
> +    <a target="_blank" href="<%= admin_question_path(gist.question) %>"><%= gist.question.text.truncate(25) %></a>
спасибо, тут перемудрила. почему-то мне казалось, что в link_to это будет выглядеть очень громоздко, чем в а

2018-12-10 16:03 UTC, iBublik commented on Gemfile
> +gem 'sawyer'
?

2018-12-10 16:03 UTC, iBublik commented on app/models/answer.rb
> +  #validate :validate_answers_length, on: create
?

2018-12-10 16:03 UTC, iBublik commented on app/services/gist_question_service.rb
> +    @client = client || Octokit::Client.new(access_token: ENV['GITHUB_TOKEN'])
А чем предыдущая форма записи не устраивала. Как по мне, она лучше суть отражала

2018-12-10 16:03 UTC, iBublik commented on app/services/gist_question_service.rb
> +  def success?
Так конечно можно делать, но лучше чтоб объект оставался "чистым" после использования - так его с уверенностью можно вызывать заново, не боясь что какие-то данные останутся от предыдущего использования. Т.е. call должен вернуть объект, у которого есть все необходимые данные + метод success? для определения успеха.

2018-12-10 16:03 UTC, iBublik commented on app/views/admin/gists/_gist.html.erb
> +    <%= link_to 'Gist URL', gist.gist_url, target: :blank %>
Текстом ссылки должен быть хэш гиста

2018-12-10 16:03 UTC, iBublik commented on app/views/shared/_flash.html.erb
> +   <%= content_tag :div, sanitize(message), class: [:alert, alert_for(type)]%>
Можно еще было пометить строку как безопасную - `message.html_safe`

2018-12-10 16:04 UTC, iBublik approved these changes

2018-12-13 14:00 UTC, Ellerden commented on app/services/gist_question_service.rb
> +    @client = client || Octokit::Client.new(access_token: ENV['GITHUB_TOKEN'])
это я пыталась откатиться во всем к тому что показывали в скринкасте, чтобы понять почему у меня не обрабатывает success. я разобралась, верну default_client, да он лучше отражает суть

2018-12-13 14:46 UTC, merged