Timertasks
Ellerden/Test-Guru pull request #20
Opened 2018-12-24 12:07 UTC by Ellerden

2018-12-24 16:46 UTC, iBublik requested changes
Нельзя слепо доверять данным, пришедшим с фронта. Опытный пользователь может посмотреть в консоль, увидеть url-ы и начать отправлять запросы вручную. На бэке нужно проверять, что время на прохождение еще не вышло

2018-12-24 16:46 UTC, iBublik commented on app/assets/javascripts/utilities/users_timer.js
> +        window.location.replace('/participations/' + participationId + '/result');
Нужно не просто отправлять на страницу результата, а завершать прохождение теста (выдавать бейджи, отправлять письма и т.д.). Последний ответ пользователя следует принять

2018-12-24 16:46 UTC, iBublik commented on app/assets/javascripts/utilities/users_timer.js
> +  clearInterval(timer);
Полагаться на глобальное состояние страницы конечно не очень хорошо

2018-12-24 16:46 UTC, iBublik commented on app/controllers/admin/tests_controller.rb
> +    params.require(:test).permit(:title, :level, :category_id, :recommended_time)
Это не рекомендуемое время, ты ведь завершаешь тест если время вышло)

2018-12-24 16:46 UTC, iBublik commented on app/models/test.rb
> +  def hours_to_pass_test
Зачем эту логику дублировать и на фронте, и на бэке? На фронт можно отправлять оставшееся число секунд, пускай уже он это форматирует

2018-12-24 16:46 UTC, iBublik commented on app/models/test.rb
> +  def time
Зачем еще и общее время отдельно?

2018-12-24 18:31 UTC, Ellerden commented on app/models/test.rb
> +  def time
я использую это в выводе нескольких вьюх (всех созданных тестов для админа) и для пользователя, показывая время прохождения. Сначала у меня это было в самих вьюхах, но я как раз решила, что лучше всю такую логику убрать в модель.

2019-01-09 05:55 UTC, iBublik requested changes

2019-01-09 05:55 UTC, iBublik commented on app/controllers/participations_controller.rb
> +    redirect_to result_participation_path(@participation), alert: t('.no_time_left') unless @participation.time_left?
У тебя получается, что по истечению времени пользователю не отправляются письма, не выдаются бейджи и тд. Это нужно делать - даже если время вышло, надо принимать последний ответ

2019-01-09 05:55 UTC, iBublik commented on app/models/participation.rb
> +    (Time.current.to_i - created_at.to_i) < test.time_to_pass
Насколько я помню, при вычитании времени итак integer получается

2019-01-09 05:55 UTC, iBublik commented on app/types/seconds_type.rb
> +    values = datetime.values
Чтоб код был самодокументируемым - `hours, minutes = datetime.values.last(2)`

2019-01-09 05:55 UTC, iBublik commented on app/types/seconds_type.rb
> +    values[3] * 60 + values[4] * 60
Часы надо на 3600 умножать. А можно еще хитрее поступить - в Rails пропатчен класс Integer, у него есть методы `hours/minutes`, можно писать `10.hours + 5.minutes`

2019-01-12 20:53 UTC, iBublik commented on app/assets/javascripts/utilities/users_timer.js
> +      var button = document.getElementById('btnnext');
Можно было просто форму засабмитить

2019-01-12 20:53 UTC, iBublik commented on app/controllers/participations_controller.rb
> +    if @participation.completed? || @participation.time_over?
Теперь можно будет продолжать слать ответы после того как время вышло. Лучше в методе `accept` после того, как время вышло, просто помечать тест как завершенный и после этого не принимать ответы. Т.е. выставить current_question в nil, и после этого даже если что-то придется в accept, ничего не делать

2019-01-12 20:53 UTC, iBublik commented on app/models/participation.rb
> +    (Time.current - created_at) >= test.time_to_pass if test.time_to_pass
Используй в условии предикат `time_to_pass?` - так более читабельно

2019-01-12 20:53 UTC, iBublik commented on app/models/test.rb
> +  def time_hours_minutes
Это логика отображения и ей не место в модели

2019-01-12 20:53 UTC, iBublik commented on app/types/seconds_type.rb
> +    hours.hour.to_i + minutes.minute.to_i
Можно сложить, а у результата уже вызвать to_i

2019-01-16 18:15 UTC, merged