Badgestasks
Ellerden/Test-Guru pull request #21
Opened 2019-01-11 19:59 UTC by Ellerden

2019-01-12 21:21 UTC, iBublik requested changes

2019-01-12 21:21 UTC, iBublik commented on app/assets/javascripts/utilities/set_recommended_time_to_test.js
> +  var control = document.querySelector('.timer');
Это явно не относится к этому PR

2019-01-12 21:21 UTC, iBublik commented on app/controllers/admin/badges_controller.rb
> +    @badges = Badge.all
Не стоит такое выносить в before_action. Это нужно в одном экшне, получается логика размазывается

2019-01-12 21:21 UTC, iBublik commented on app/controllers/admin/rules_controller.rb
> +class Admin::RulesController < Admin::BaseController
Отдельное создание правил - хорошо с точки зрения нормализации данных, но плохо с точки зрения простоты. Можно было ограничиться простым enum-ом и хранить тип правила в той же модели, что и сами бейджи

2019-01-12 21:21 UTC, iBublik commented on app/controllers/user_badges_controller.rb
> +    @not_rewarded_badges = @all_badges - @badges
А зачем под такое отдельный контроллер? Можно было бы сделать 1 контроллер с фильтрами - все, полученные, неполученные

2019-01-12 21:21 UTC, iBublik commented on app/helpers/rules_helper.rb
> +    content_tag(:h1, rule.persisted? ? t('.edit_rule') : t('.new_rule'))
Имеет смысл сделать 1 хелпер, отличается только выводимый текст. Можно параметром передавать или даже вычислять из класса объекта

2019-01-12 21:21 UTC, iBublik commented on app/models/badge.rb
> +  before_save :default_image
`set_default_image`

2019-01-12 21:21 UTC, iBublik commented on app/models/rule.rb
> +    [I18n.t('.rules.whole_category'), 'whole_category'],
Переводы не стоит хранить в самой модели

2019-01-12 21:21 UTC, iBublik commented on app/models/rule.rb
> +  #to properly show it in badges creation selector form
Модели про формы вообще ничего не знают. Это правильнее в декораторы выносить, но т.к. мы пока стараемся придерживаться стандартного MVC стека, то используй хелперы

2019-01-12 21:21 UTC, iBublik commented on app/models/test.rb
> +    Test.where('level = ?', level)
Зачем это делать методом класса? Это же обычный скоуп

2019-01-12 21:21 UTC, iBublik commented on app/models/user.rb
> +    Test.joins(:participations).where(tests: { level: level }).where(participations: { user_id: self.id })
Жутко переусложненный способ получить все тесты пользователя. То же самое - `tests.where(level: level)`

2019-01-12 21:21 UTC, iBublik commented on app/models/test.rb
>      Test.joins(:category).where(categories: { title: category }).order(title: :desc).pluck(:title)
Убери `Test` отсюда, лишнее

2019-01-12 21:21 UTC, iBublik commented on app/models/user.rb
> +    Test.joins(:participations, :category).where(categories: { title: category }).where(participations: { user_id: self.id })
`tests.by_category(category)`

2019-01-12 21:21 UTC, iBublik commented on app/models/user.rb
> +    Participation.where(user_id: self.id, test_id: test_id)
`participations.where(test: test)`

2019-01-12 21:21 UTC, iBublik commented on app/services/badges_reward_service.rb
> +  def achieve_badge(badge)
Если оставлять этот метод, то он явно не публичный

2019-01-12 21:21 UTC, iBublik commented on app/services/badges_reward_service.rb
> +    @rewarded = true
Все эти параметры - это усложнение. Можно просто сделать, чтобы сервис возвращал список бейджей, которые можно выдать пользователю. Если список не пустой - значит пользователь "награжден". К тому же, такой подход гибче - со списком можно сделать что угодно: отренедрить на странице, отправить письмом, выдать бейджи пользователю.

2019-01-12 21:21 UTC, iBublik commented on app/services/badges_reward_service.rb
> +    if @participation.success?
`return unless @participation.success?`

2019-01-12 21:21 UTC, iBublik commented on app/services/badges_reward_service.rb
> +  def passed_first_try_rule?(_rule)
Все это в приватные методы

2019-01-12 21:21 UTC, iBublik commented on app/views/admin/rules/_form.html.erb
> +            <%= f.collection_radio_buttons :params, (1..5).map{ |n| [n, n] }, :first, :last, class: "form-control" %>
Насколько я помню, если просто передать перечислимое (тот же рейндж), то и текстом и значением будет элемент коллекции

2019-01-12 21:21 UTC, iBublik commented on app/models/badge.rb
> +    self.route ||= 'badges/default.png'
Странное название поля. Это же `image_path`

2019-01-12 21:21 UTC, iBublik commented on db/migrate/20190109100108_create_user_badges.rb
> +      add_column :rules, :description, :string, null: false
Нельзя такие дейтсвия делать внутри `create_table`. Даже если это работает, то это сильно путает

2019-01-16 18:21 UTC, Ellerden commented on app/controllers/admin/badges_controller.rb
> +    @badges = Badge.all
ага, спасибо. у меня сначала был еще один какой-то вспомогательный метод, который тоже использовал @badges. но потом я от него отказалась, а логика осталась.

2019-01-16 19:44 UTC, Ellerden commented on db/migrate/20190109100108_create_user_badges.rb
> +      add_column :rules, :description, :string, null: false
я тут как раз исходила из того, что не надо плодить много миграций. и поэтому запихнула все это в одну последнюю миграцию, т.к. все это так или иначе относилось к бейджам

2019-01-16 19:45 UTC, Ellerden commented on db/migrate/20190109100108_create_user_badges.rb
> +      add_column :rules, :description, :string, null: false
разобью это на 2 миграции - одну про create_user_badges, другую про update_rules

2019-01-18 05:51 UTC, iBublik commented on app/models/test.rb
> +    Test.where('level = ?', level)
> Зачем это делать методом класса? Это же обычный скоуп

☝️

2019-01-18 05:51 UTC, iBublik commented on app/services/badges_reward_service.rb
> +    Badge.select{ |badge| send("passed_#{badge.rule_name}_rule?", badge.rule_params)}
Пробелы вокруг фигурных скобок
Рекомендую использовать rubocop, чтоб не было таких замечаний

2019-01-18 05:51 UTC, iBublik commented on app/services/badges_reward_service.rb
> +  # once achieved it will be awarded with every test, even when it's not from the category.
Эту проверку имеет смысл сделать самой 1й и сразу выходить из метода, если она не прошла (guard clause)

2019-01-18 05:51 UTC, iBublik commented on app/services/badges_reward_service.rb
> +    tests_by_level != 0 && (@participation.test.level == level.to_i) && (@user.test_passed_by_level(level).uniq.count == tests_by_level)
Разбей на несколько строк

2019-01-18 05:51 UTC, iBublik commented on app/views/admin/badges/_form.html.erb
> +              <%= f.collection_radio_buttons :rule_params, (1..5), :to_s, :to_s, class: "form-control" %>
Можно без скобок
Это конечно уже мелочи UX, но я бы обычный числовой инпут сделал с ограничением по минимальному и максимальному значениям

2019-01-18 05:51 UTC, iBublik commented on db/migrate/20190117185131_add_indexes_to_badges.rb
> +    add_index(:badges, [:name, :rule_name, :rule_params], unique: true)
А зачем этот индекс? Если нельзя создать правило с повторяющимися rule_name и rule_params, то естественно нельзя будет создать правило с повторяющимися rule_name и rule_params дажеесли у них будет разное имя.

2019-01-18 05:51 UTC, iBublik commented on db/migrate/20190109100108_create_user_badges.rb
> +      add_column :rules, :description, :string, null: false
Я про то, что у тебя это описано внутри блока `create_table`. Если бы это было после create_table, то вопросов бы не было

2019-01-18 05:52 UTC, iBublik approved these changes

2019-01-18 14:56 UTC, merged