create associations between models, create new column -  author for test
Ellerden/Test-Guru pull request #6
Opened 2018-10-05 23:30 UTC by Ellerden

associations in models, a new column (author) in tests which is linked to users.

2018-10-07 10:08 UTC, vkurennov requested changes

2018-10-07 10:08 UTC, vkurennov commented on app/models/user.rb
> +  has_many :tests, through: :participations
Чтобы работала ассоциация has_many through, нужно сначала добавить has_many-ассоциацию с моделью, которая стоит в through, т.е. с participations

2018-10-07 10:08 UTC, vkurennov commented on app/models/user.rb
> +  has_many :tests, class_name: 'Test', foreign_key: :author_id
Не могут 2 ассоциации иметь одно и то же имя, вторая перезапишет первую, нужно изменить имена.

2018-10-07 16:14 UTC, Ellerden commented on app/models/user.rb
> +  has_many :tests, through: :participations
спасибо, это почему-то, как и другие прописанные ассоциации, застряло в локальной версии гита, но не перенеслось в ремоут. пофиксила это и проверила - теперь точно все есть.

2018-10-08 09:30 UTC, iBublik approved these changes

2018-10-08 09:30 UTC, iBublik commented on app/models/category.rb
> +  has_many :tests
При создании `has_*` ассоциации стоит указывать что делать с дочерними записями при удалении родителя (опция dependent). Сейчас ты не сможешь удалить категорию, у которой есть тесты

2018-10-08 09:30 UTC, iBublik commented on app/models/test.rb
>      Test.joins('INNER JOIN categories ON categories.id = tests.category_id')
Этот запрос можно упростить использованием ассоциаций

2018-10-08 09:30 UTC, iBublik commented on app/models/user.rb
>      Test.joins('INNER JOIN participations ON participations.user_id = id')
Здесь можно значительно облегчить код, используя ассоциацию

2018-10-08 09:30 UTC, iBublik commented on db/seeds.rb
> +tests = Test.create!([{ title: 'Кто что снял?', level: 2, category_id: categories[4].id,
Теперь можно передавать не id, а сами записи - `category: categories[4]`

2018-10-09 19:33 UTC, merged