Validationscopetasks
Ellerden/Test-Guru pull request #8
Opened 2018-10-10 08:58 UTC by Ellerden

2018-10-10 12:51 UTC, iBublik requested changes

2018-10-10 12:51 UTC, iBublik commented on app/models/answer.rb
> +  scope :right, -> { where(correct: true) }
Ассоциации, валидации, скоупы - это все логически отдельные блоки. Следует их разделять пустыми строками
С точки зрения английского языка, правильнее использовать название `correct`

2018-10-10 12:51 UTC, iBublik commented on app/models/answer.rb
> +    return if question.answers.length <= 4
Используй `count`, чтоб не грузить все вопросы в память

2018-10-10 12:51 UTC, iBublik commented on app/models/answer.rb
> +  validate :answers_length
Эта валидация не дает обновить ответ, если у вопроса набралось 4 ответа. Нужно вызывать ее только при создании ответа

2018-10-10 12:51 UTC, iBublik commented on app/models/category.rb
> +  default_scope { order(title: :asc) }
Скоуп по умолчанию глобально меняет поведение запросов у данной модели. Это важное изменение, следует его на виду держать - в самом верху класса

2018-10-10 12:51 UTC, iBublik commented on app/models/test.rb
> +                          .order(title: :desc).pluck(:title)
Скоупы должны быть способны выстраиваться в цепочку вызовов - `Test.easy.created_last_week.where(...)`. Для этого скоуп должен вовзращать ActiveRecord::Relation (это как раз то что возвращают методы запросов `where`, `order` и т.д.). У тебя тут возвращается массив, так что после вызова этого скоупа другой уже не применить. Либо оставь метод класса, либо часть выдели в скоуп, а часть оставь в методе класса

2018-10-10 12:51 UTC, iBublik commented on app/models/user.rb
> +  validates_uniqueness_of :email, :username
Используй новый формат записи валидаций - он более гибкий

2018-10-10 12:51 UTC, iBublik commented on app/models/test.rb
> +  validates :title, uniqueness: { scope: :level }, on: :create
Почему только при создании?
Для лучшей работы этой валидации следует добавить уникальный индекс в базе

2018-10-10 13:52 UTC, Ellerden commented on app/models/answer.rb
> +  scope :right, -> { where(correct: true) }
я не использовала correct чтобы не дублировать - т.к. correct поле есть в инстансах, но т.к. scope  это как бы метод класса, то это не дублирование. заменю на correct

2018-10-10 13:56 UTC, Ellerden commented on app/models/answer.rb
> +    return if question.answers.length <= 4
я думала, что length как раз и является здесь идентичным Count. 
когда я вызываю length - объекты загружаются в память, а когда Count - то просто возвращается их количество?

2018-10-10 14:09 UTC, Ellerden commented on app/models/test.rb
> +                          .order(title: :desc).pluck(:title)
спасибо, не учла этот момент.

2018-10-10 17:19 UTC, iBublik commented on app/models/answer.rb
>    def answers_length
Сделай метод приватным. И методы-валидации обычно назвают с префиксом `validate` или `check`

2018-10-10 17:19 UTC, iBublik commented on app/models/answer.rb
> +    return if question.answers.count <= 4
Сейчас валидация пропустит создание 5 ответа

2018-10-10 17:19 UTC, iBublik commented on app/models/test.rb
> +     Test.joins(:category).order(title: :desc).pluck(:title)
А почему не использовать тут скоуп `by_category`?

2018-10-10 17:19 UTC, iBublik commented on db/migrate/20181010142622_add_tests_title_uniqueness.rb
> +  def change
А где собственно код миграции?

2018-10-11 07:05 UTC, iBublik commented on app/models/answer.rb
> +    return if question.answers.length <= 4
Да, count всегда делает запрос в базу, length всегда загружает их в память, size комбинирует эти 2 подхода и действует в зависимости от состояния. На length лучше не полагаться - записи могли быть загружены ранее, нам надо всегда смотреть на текущее состояние базы

2018-10-15 18:24 UTC, merged