Controllertasks
Ellerden/Test-Guru pull request #9
Opened 2018-10-15 18:20 UTC by Ellerden

2018-10-15 19:15 UTC, iBublik requested changes

2018-10-15 19:15 UTC, iBublik commented on app/controllers/questions_controller.rb
> +  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found
Отдели это выражение от коллбеков пустой строкой. Это логически раздельные блоки описания класса

2018-10-15 19:15 UTC, iBublik commented on app/controllers/questions_controller.rb
> +  def pluck
Что это? В стандартном REST-контроллере должны быть только CRUD операции

2018-10-15 19:15 UTC, iBublik commented on app/controllers/questions_controller.rb
> +    questions.each do |quest|
Используй `map` для преобразования коллекций

2018-10-15 19:15 UTC, iBublik commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:text, :test_id)
Связь с тестом должна происходить через ассоциации, а не через параметры. Для этого мы делали ресурс вложенным

2018-10-15 19:15 UTC, iBublik commented on app/controllers/questions_controller.rb
> +  before_action :find_test, except: [:show, :create, :destroy]
Не рекомендую использовать `except` в коллбеках. Такой коллбек начнет применяться ко всем новым экшнам, которые добавятся в контроллер - это довольно неочевидно

2018-10-15 19:15 UTC, iBublik commented on app/views/questions/new.html.erb
> +<form action="/questions" method="post">
URL для создания вопроса должен содержать id теста

2018-10-15 19:15 UTC, iBublik commented on app/views/questions/show.html.erb
> +<%= link_to 'Удалить', question_path(@question), :method => :delete %>
Это устаревший формат записи хешей, не нужно его применять

2018-10-15 19:15 UTC, iBublik commented on config/routes.rb
> +  post '/questions' =>'questions#create'
Что это за нестандартные роуты и для чего они?

2018-10-15 19:58 UTC, Ellerden commented on app/controllers/questions_controller.rb
> +  def pluck
Привет! Я ввела его, потому что надо было в задании “Просмотреть конкретный вопрос теста” и если не вводить новый рут, то не было для этого урла tests/:tests-id/questions/:id / я решила не переопределять существующий show (так как подумала, что он может понадобиться для всех вопросов всех тестов). Т.е. я правильно понимаю, что проблема только в pluck - а если я переопределю тот же рут для show, это будет ок? Или я как-то не так поняла задание?

2018-10-15 20:02 UTC, Ellerden commented on app/controllers/questions_controller.rb
> +    questions.each do |quest|
ок, хорошо

2018-10-16 12:36 UTC, iBublik commented on app/controllers/questions_controller.rb
> +   @question = @test.questions.build
Отступ поехал

2018-10-16 12:36 UTC, iBublik commented on app/controllers/questions_controller.rb
> +    questions.map { |quest| result << "#{quest.id} - #{quest.text}" }
`map` итак возвращает массив. Не нужно мутировать внешнюю переменную

2018-10-16 12:36 UTC, iBublik commented on app/views/questions/new.html.erb
> +<form action="<%= "/tests/#{@question.test.id}/questions" %>", method="post">
Можно было просто `params[:test_id]` или `@test.id`

2018-10-16 12:36 UTC, iBublik commented on app/controllers/questions_controller.rb
> +  before_action :find_test, only: %i[index pluck new create show]
pluck же больше не существует?

2018-10-16 12:36 UTC, iBublik commented on config/routes.rb
> +  get '/tests/:test_id/questions/:id(.:format)' =>'questions#show'
Видимо какой-то атавизм в задании. В show нам неважен id теста, достаточно id вопроса.

2018-10-16 12:36 UTC, iBublik commented on app/controllers/questions_controller.rb
> +    if @question.test_id == @test.id
В реальности, если бы нам было важно удостовериться, что вопрос принадлежит конкретному тесту, то код бы так выглядел - `@question = @test.questions.find(params[:id])`

2018-11-05 01:20 UTC, merged